---
title: "NYC Flight analysis"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: 
      version: 4
      bootswatch: minty
      
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, rows.print=25)

library(nycflights13)  # dataset
library(tidyverse)
library(plotly)        # Interactive 
library(RColorBrewer)  # colors
library(DT)            # nice view tables

theme_set(theme_classic())

# display.brewer.all(colorblindFriendly = TRUE)
# display.brewer.pal(n = 8, name = 'Dark2')
# View a single RColorBrewer palette by specifying its name
colors <- as.list(brewer.pal(n = 8, name = 'Dark2'))
objects <- c(
  "min",
  "q05",
  "q25",
  "median",
  "q75",
  "q95",
  "max",
  "bins"
)
names(colors) <- objects
```



# Delay Analysis

## Col {.tabset .tabset-fade}
   
### Delay summary

```{r}
arr_delay_summary <- flights %>% 
  summarise(
    min = min(arr_delay, na.rm = TRUE),
    q05 = quantile(arr_delay, probs = 0.05, na.rm = TRUE),
    q25 = quantile(arr_delay, probs = 0.25, na.rm = TRUE),
    median = quantile(arr_delay, probs = 0.50, na.rm = TRUE),
    q75 = quantile(arr_delay, probs = 0.75, na.rm = TRUE),
    q95 = quantile(arr_delay, probs = 0.95, na.rm = TRUE),
    max = max(arr_delay, na.rm = TRUE)
  )
datatable(arr_delay_summary, rownames = FALSE)
```

### Histogram

```{r}
v_line_size = 1.2
label_height = 150000
pl <- ggplot(flights) + 
  aes(x = arr_delay) +
  geom_histogram(fill = colors$bin, color = "black", bins = 40) +
  geom_vline(xintercept = arr_delay_summary$min, colour = colors$min, size = v_line_size)
  # geom_vline(xintercept = arr_delay_summary$q25, colour = colors$q25, size = v_line_size) +
  # geom_vline(xintercept = arr_delay_summary$median, colour = colors$median, size = v_line_size) +
  # geom_vline(xintercept = arr_delay_summary$q75, colour = colors$q75, size = v_line_size) +
  # geom_vline(xintercept = arr_delay_summary$max, colour = colors$max, size = v_line_size) +
  # geom_label(aes(x = arr_delay_summary$min, y = label_height, label = "min"))
  # geom_label(aes(x = arr_delay_summary$q25, y = label_height, label = "q25")) +
  # geom_label(aes(x = arr_delay_summary$median, y = label_height, label = "q50")) +
  # geom_label(aes(x = arr_delay_summary$q75, y = label_height, label = "q75")) +
  # geom_label(aes(x = arr_delay_summary$max, y = label_height, label = "max"))
pl
```


### Histogram detail

```{r}
ggplotly(
  pl +
    xlim(arr_delay_summary$q05, arr_delay_summary$q95) 
)
```


### Boxplot

```{r}
pl <- ggplot(flights) + 
  aes(x = arr_delay) +
  geom_boxplot(fill = colors$bin, color = "black")
pl
```


### Boxplot detail

```{r}
pl +
  xlim(arr_delay_summary$q05, arr_delay_summary$q95) +
  geom_vline(xintercept = arr_delay_summary$min, colour = colors$min, size = v_line_size) + 
  geom_vline(xintercept = arr_delay_summary$q25, colour = colors$q25, size = v_line_size) + 
  geom_vline(xintercept = arr_delay_summary$median, colour = colors$median, size = v_line_size) + 
  geom_vline(xintercept = arr_delay_summary$q75, colour = colors$q75, size = v_line_size) + 
  geom_vline(xintercept = arr_delay_summary$max, colour = colors$max, size = v_line_size)
```


### Density

```{r}
pl <- ggplot(flights) + 
  aes(x = arr_delay) +
  geom_density(fill = colors$bin, color = "black")
pl
```


### Density detail

```{r}
pl +
  xlim(arr_delay_summary$q05, arr_delay_summary$q95) +
  geom_vline(xintercept = arr_delay_summary$min, colour = colors$min, size = v_line_size) + 
  geom_vline(xintercept = arr_delay_summary$q25, colour = colors$q25, size = v_line_size) + 
  geom_vline(xintercept = arr_delay_summary$median, colour = colors$median, size = v_line_size) + 
  geom_vline(xintercept = arr_delay_summary$q75, colour = colors$q75, size = v_line_size) + 
  geom_vline(xintercept = arr_delay_summary$max, colour = colors$max, size = v_line_size)
```



## Col {.tabset .tabset-fade}



### Timeseries

```{r eval=FALSE, include=FALSE}
arr_delay_ts <- flights %>% 
  group_by(year, month, carrier) %>% 
  summarise(arr_delay = sum(arr_delay, na.rm = TRUE))
ts_pl <- arr_delay_ts %>% 
  ggplot() +
  aes(x = month, y = arr_delay, color = carrier) +
  geom_line(stat = "identity", size = 1)
ggplotly(ts_pl)
```


```{r echo=FALSE}
arr_delay_ts <- flights %>% 
  unite(col = date, year, month, day) %>% 
  mutate(date = lubridate::ymd(date)) %>% 
  mutate(month = lubridate::ceiling_date(date, "month")) %>% 
  group_by(month, carrier) %>% 
  summarise(arr_delay = sum(arr_delay, na.rm = TRUE))
ts_pl <- arr_delay_ts %>% 
  ggplot() +
  aes(x = month, y = arr_delay, color = carrier) +
  geom_line(stat = "identity", size = 1)
ggplotly(ts_pl)
```




### Flights per carrier

```{r}
ggplot(flights) +
  aes(x = carrier) + 
  geom_bar(fill = colors$bins)
```


### Dep/arr relation

```{r}
delay_scatter_plot <- 
  flights %>% 
  sample_frac(0.10) %>% 
  ggplot() + 
  aes(x = dep_delay, y = arr_delay) + 
  geom_point(alpha = 0.10)
delay_scatter_plot +
  geom_smooth(se = FALSE, method = "lm", formula = y~x)
```

### Flights per carrier per month

```{r}
ggplot(flights) +
  aes(x = carrier, fill = factor(month)) + 
  geom_bar(position = "stack", color = "gray")
```


### Flights per month

```{r}
flights %>% 
  mutate(month = factor(month)) %>% 
  ggplot() +
  aes(x = carrier, fill = month) + 
  geom_bar(position = "dodge")

```
