---
title: "03-Data-visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dslabs)
data(murders)
```

## Empty plot

```{r}
ggplot(data = murders)
```


## Cheat sheet


```{r}
ggplot(data = murders) +
  aes(x = population/10^6, y = total) +
  geom_point()
```


```{r}
p <- ggplot(data = murders)
```


```{r}
p + 
  geom_point(aes(population/10^6, total), size = 3) +
  geom_text(aes(population/10^6, total, label = abb), nudge_x = 1.5)
```


```{r}
p + 
  geom_point(aes(population/10^6, total), size = 3) +
  geom_text(aes(population/10^6, total, label = abb), nudge_x = 0.05) +
  scale_x_log10() +
  scale_y_log10()
```


```{r}
p + 
  geom_point(aes(population/10^6, total), size = 3) +
  geom_text(aes(population/10^6, total, label = abb), nudge_x = 0.05) +
  scale_x_log10() +
  scale_y_log10() +
  xlab("Populations in millions (log scale)") + 
  ylab("Total number of murders (log scale)") +
  ggtitle("US Gun Murders in 2010")
```


```{r}
p + 
  geom_point(aes(population/10^6, total, color = region), size = 3) +
  geom_text(aes(population/10^6, total, label = abb), nudge_x = 0.05) +
  scale_x_log10() +
  scale_y_log10() +
  xlab("Populations in millions (log scale)") + 
  ylab("Total number of murders (log scale)") +
  ggtitle("US Gun Murders in 2010")
```



```{r}
r <- murders %>% 
  summarize(rate = sum(total) /  sum(population) * 10^6) %>% 
  pull(rate)

r
```

```{r}
p + 
  geom_point(aes(population/10^6, total, color = region), size = 3) +
  geom_text(aes(population/10^6, total, label = abb), nudge_x = 0.05) +
  scale_x_log10() +
  scale_y_log10() +
  xlab("Populations in millions (log scale)") + 
  ylab("Total number of murders (log scale)") +
  ggtitle("US Gun Murders in 2010") +
  geom_abline(intercept = log10(r))
```


```{r}
library(ggthemes)
library(ggrepel)
p + 
  geom_point(aes(population/10^6, total, color = region), size = 3) +
  geom_text_repel(aes(population/10^6, total, label = abb), nudge_x = 0.05) +
  scale_x_log10() +
  scale_y_log10() +
  xlab("Populations in millions (log scale)") + 
  ylab("Total number of murders (log scale)") +
  ggtitle("US Gun Murders in 2010") +
  geom_abline(intercept = log10(r), lty = 2, color = "darkgrey") +
  theme_economist()
```







